
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileFilter;
import java.io.FileNotFoundException;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLClassLoader;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JViewport;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Brian
 */
public class GUI_Coverage_Tool extends javax.swing.JFrame {
    String help;
    JFileChooser jfc = null;
    File[] files = null;
    String[] fileName;
    private URL url;
    private URLClassLoader ucl;
    Class[] classes;
    Method[] methods;
    Constructor[] constructors;
    String[] parentFileName;
    String[] grandParentFileName;
    Object obj1 = new Object();
    Object[] obj = null;
    int numOfRuns = 0;
    Class[] cls1;
    private final JViewport rowHeader = new JViewport();
    FileNameExtensionFilter filter= new FileNameExtensionFilter("Class File", "class");

    /**
     * Creates new form GUI_Coverage_Tool
     */
    public GUI_Coverage_Tool()
    {
        initComponents();
        this.jScrollPane2.setRowHeader(rowHeader);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
        );

        jToolBar1.setRollover(true);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\brian\\Documents\\Fall 2023\\SWENG 431\\add folder.png")); // NOI18N
        jLabel1.setToolTipText("Open Folder");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 4));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jToolBar1.add(jLabel1);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\brian\\Documents\\Fall 2023\\SWENG 431\\remove folder.png")); // NOI18N
        jLabel2.setToolTipText("Remove Selection");
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 4));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jToolBar1.add(jLabel2);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\brian\\Documents\\Fall 2023\\SWENG 431\\manual.png")); // NOI18N
        jLabel4.setToolTipText("Help");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 4));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jToolBar1.add(jLabel4);

        jLabel3.setText("Run");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 4));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jToolBar1.add(jLabel3);

        jScrollPane2.setViewportView(jList2);

        jMenu1.setText("File");

        jMenuItem2.setText("Open Folder");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem3.setText("Remove Selection");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.getJfc();

        this.variablesInitializer();

        this.directoryParser(1);
        this.jList1.setListData(fileName);
        this.jList2.setListData(new String[0]);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.getJfc();

        this.variablesInitializer();

        this.directoryParser(0);

        this.jList1.setListData(fileName);
        this.jList2.setListData(new String[0]);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        try {
            // TODO add your handling code here:
            Scanner inFs = new Scanner(new File("C:\\Users\\brian\\Documents\\Fall 2023\\SWENG 431\\Lab 11 GUI Test Tool\\src\\Lab 11 Help.txt"));
            help = inFs.nextLine() + "\n";
            while(inFs.hasNextLine())
            {
                help += inFs.nextLine() + "\n";     
            }
        } catch (FileNotFoundException ex) {
            System.out.println(ex.getMessage());
        }
        JFrame helpFrame = new JFrame();
        JTextArea helpText = new JTextArea();
        helpText.setEnabled(false);
        helpText.setBackground(Color.white);
        helpText.setText(help);
        helpText.setBackground(Color.WHITE);
        helpText.setDisabledTextColor(Color.blue);
        Font font = helpText.getFont();
        float size = font.getSize() + 1.0f;
        helpText.setFont(font.deriveFont(size));
        helpText.setLineWrap(true);
        helpFrame.setSize(650, 250);
        helpFrame.setVisible(true);
        helpFrame.add(helpText);       
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
            int index = this.jList1.getSelectedIndex();
        
        methods = classes[index].getDeclaredMethods();
        constructors = classes[index].getConstructors();

            int i;
            Class[] cls;
            int j;
            int k = 0;
            
        String[] str = new String[this.constructors.length + this.methods.length];

        for(i = 0; i < this.constructors.length; ++i) 
        {
            cls = this.constructors[i].getParameterTypes();
            str[i] = this.constructors[i].getName() + "(";

            for(j = 0; j < cls.length; ++j) 
            {
                if (j == cls.length - 1) 
                {
                    str[i] = str[i] + cls[j].getName();
                } else 
                {
                    str[i] = str[i] + cls[j].getName() + ",";
                }
            }
            k++;
            str[i] = str[i] + ")";
        }
               
        for(i = 0; i < this.methods.length; ++i) 
        {
            cls = this.methods[i].getParameterTypes();
            str[i + k] = this.methods[i].getReturnType().getName() + " " + this.methods[i].getName() + "(";

            for(j = 0; j < cls.length; ++j) 
            {
                if (j == cls.length - 1) 
                {
                    str[i + k] = str[i + k] + cls[j].getName();
                } 
                else 
                {
                    str[i + k] = str[i + k] + cls[j].getName() + ",";
                }
            }

                str[i + k] = str[i + k] + ")";
        }

        this.jList2.setListData(str);
    }//GEN-LAST:event_jList1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        int idx = this.jList2.getSelectedIndex();
        int index = this.jList1.getSelectedIndex();
        
        
        if (idx >= this.constructors.length && obj == null)
        {
            JOptionPane.showMessageDialog(this.jScrollPane2, 
                    "Create an object first using any of the listed constructors");
        }
        if (idx < this.constructors.length)
        {
            cls1 = this.constructors[idx].getParameterTypes();
            obj = this.class2object(cls1);

            try 
            {
                this.obj1 = this.constructors[idx].newInstance(obj);
            } 
            catch (Exception ex) 
            {
                System.out.println(ex + " \n****Could not create class****");
            }
        }
        
        if (idx >= this.constructors.length && obj != null)
        {
            Class[] mtd = this.methods[idx - this.constructors.length].getParameterTypes();
            obj = this.class2object(mtd);

            try 
            {
                Object outcome = this.methods[idx - this.constructors.length].invoke(this.obj1, obj);
                numOfRuns++;
                if (outcome != null) 
                {
                    System.out.println(outcome.toString() + "\n");
                }
                else 
                {
                    System.out.println("null\n");
                }
            
            } 
            catch (Exception var6) 
            {
                System.out.println(var6 + " \n****Couldn't call method****");
            }
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.obj = null;
        this.obj1 = null;
        this.methods = null;
        this.fileName = null;
        this.jfc = null;
        this.parentFileName = null;
        this.grandParentFileName = null;
        this.constructors = null;
        this.url = null;
        this.ucl = null;
        this.classes = null;
        this.jList1.setListData(new String[0]);
        this.jList2.setListData(new String[0]);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.obj = null;
        this.obj1 = null;
        this.methods = null;
        this.fileName = null;
        this.jfc = null;
        this.parentFileName = null;
        this.grandParentFileName = null;
        this.constructors = null;
        this.url = null;
        this.ucl = null;
        this.classes = null;
        this.jList1.setListData(new String[0]);
        this.jList2.setListData(new String[0]);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args)
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Coverage_Tool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Coverage_Tool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Coverage_Tool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Coverage_Tool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                new GUI_Coverage_Tool().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables

    private Object[] class2object(Class[] cls) 
    {
        Object[] obj = new Object[cls.length];

        for(int j = 0; j < cls.length; ++j) {
            if (!cls[j].isPrimitive()) 
            {
                NewJDialog id2 = new NewJDialog(cls[j]);
                id2.setVisible(true);
                obj[j] = id2.getObject();
            } else {
                NewJDialog id1 = new NewJDialog(cls[j]);
                id1.setVisible(true);
                obj[j] = id1.getObject();
            }
        }

        return obj;
    }
    
    private File[] getMatchingFiles(File parent, final String extension) 
    {
        return parent.listFiles(new FileFilter()
        {

            public boolean accept(File dir)
            {
                String name = dir.getName();
                return name.endsWith(extension);
            }
        });
    }
    public static Class chooser(File f, Class c, String str1,
                                String str2, String str3, int index) throws MalformedURLException, ClassNotFoundException
    {
        while (c == null)
        {
            URL url;
            URLClassLoader ucl;
            if (index == 0)
            {
                url = f.getParentFile().toURI().toURL();
                URL[] urla = {url};
                ucl = new URLClassLoader(urla);
                c = Class.forName(str1, true, ucl);
            }
            if (index == 1)
            {
                url = f.getParentFile().getParentFile().toURI().toURL();
                URL[] urla = {url};
                ucl = new URLClassLoader(urla);
                c = Class.forName(str2 + "." + str1, true, ucl);
            }
            if (index == 2)
            {
                url = f.getParentFile().getParentFile().getParentFile().toURI().toURL();
                URL[] urla = {url};
                ucl = new URLClassLoader(urla);
                c = Class.forName(str3 + "." + str2 + "." + str1, true, ucl);
            }
            index++;
        }
        return c;
    }

    public void getJfc()
    {
        if (jfc == null)
        {
            jfc = new JFileChooser("C://Users//brian//Documents//FALL 2023//SWENG 431");
            jfc.setFileSelectionMode(2);
            jfc.setMultiSelectionEnabled(true);
            jfc.setFileFilter(filter);
        }

        if (jfc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION)
        {
            files = jfc.getSelectedFiles();
        }

        if (files[0].isDirectory())
        {
            files = getMatchingFiles(files[0], "class");
        }
    }

    public void variablesInitializer()
    {
        if (fileName == null)
            fileName = new String[files.length];
        if (parentFileName == null)
            parentFileName = new String[files.length];
        if (grandParentFileName == null)
            grandParentFileName = new String[files.length];
        if (classes == null)
            classes = new Class[files.length];
    }

    public void directoryParser(int index)
    {
        int i = 0;
        for (File f : files)
        {
            fileName[i] = f.getName().split("\\.")[0];
            parentFileName[i] = f.getParentFile().getName();
            grandParentFileName[i] = f.getParentFile().getParentFile().getName();

            try
            {
                classes[i] = chooser(files[i], classes[i], fileName[i],
                        parentFileName[i], grandParentFileName[i], index);
            } catch (MalformedURLException | ClassNotFoundException e)
            {
                System.out.println(e.getMessage());
            }

            i++;
        }
    }
}
