import com.sun.jdi.Bootstrap;
import com.sun.jdi.VirtualMachine;
import com.sun.jdi.connect.Connector;
import com.sun.jdi.connect.LaunchingConnector;

import java.awt.Color;
import java.awt.Font;
import java.io.*;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLClassLoader;
import java.util.Hashtable;
import java.util.Map;
import java.util.Scanner;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Brian
 */
public class GUI_Coverage_Tool extends javax.swing.JFrame {
    String help;
    int returnVal;
    JFileChooser jfc = new JFileChooser("C://Users//brian//Documents//FALL 2023//SWENG 431");
    File[] files = null;
    File dir;
    String[] fileName;
    private URL url;
    URL[] urls = new URL[1];
    private URLClassLoader ucl;
    VirtualMachine vm;
    Class[] classes;
    Method[] methods;
    Constructor[] constructors;
    String[] parentFileName;
    String[] grandParentFileName;
    JTextArea jColHeader = new JTextArea();
    JTextArea jTextArea2 = new JTextArea();
    MyThread mt;
    FileNameExtensionFilter filter= new FileNameExtensionFilter("Class File", "class");
    MyFileNameFilter myFileNameFilter = new MyFileNameFilter();

    /**
     * Creates new form GUI_Coverage_Tool
     */
    public GUI_Coverage_Tool()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSplitPane1 = new JSplitPane();
        jList1 = new javax.swing.JList<>();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        this.jColHeader.setText("     ");
        this.jColHeader.setBackground(Color.GRAY);
        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
        );
        this.jSplitPane1.setOneTouchExpandable(true);
        javax.swing.GroupLayout layout_ = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout_);
        layout_.setHorizontalGroup(
                layout_.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout_.createSequentialGroup()
                                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
                        .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout_.setVerticalGroup(
                layout_.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout_.createSequentialGroup()
                                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addGroup(layout_.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSplitPane1)))
        );

        jToolBar1.setRollover(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/pkg11/gui/test/tool/resources/add folder.png"))); // NOI18N
        jLabel1.setToolTipText("Open Folder");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 4));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try
                {
                    jLabel1MouseClicked(evt);
                } catch (MalformedURLException | ClassNotFoundException e)
                {
                    throw new RuntimeException(e);
                }
            }
        });
        jToolBar1.add(jLabel1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/pkg11/gui/test/tool/resources/remove folder.png"))); // NOI18N
        jLabel2.setToolTipText("Remove Selection");
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 4));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jToolBar1.add(jLabel2);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/pkg11/gui/test/tool/resources/manual.png"))); // NOI18N
        jLabel4.setToolTipText("Help");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 4));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jToolBar1.add(jLabel4);

        jButton1.setText("Run");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jScrollPane2.setViewportView(jList2);

        jMenu1.setText("File");

        jMenuItem2.setText("Open Folder");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try
                {
                    jMenuItem2ActionPerformed(evt);
                } catch (MalformedURLException | ClassNotFoundException e)
                {
                    throw new RuntimeException(e);
                }
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem3.setText("Remove Selection");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)))
        );
        this.jScrollPane2.getViewport().add(this.jTextArea2);
        this.jScrollPane2.setRowHeaderView(this.jColHeader);
        this.jScrollPane1.getViewport().add(this.jList1, (Object)null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) throws MalformedURLException, ClassNotFoundException
    {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.getJfc();

        this.directoryParser(1);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) throws MalformedURLException, ClassNotFoundException
    {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.getJfc();

        this.directoryParser(0);

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        try {
            // TODO add your handling code here:
            Scanner inFs = new Scanner(new File("C:\\Users\\brian\\Documents\\Fall 2023\\SWENG 431\\Lab 11 GUI Test Tool\\src\\Lab 11 Help.txt"));
            help = inFs.nextLine() + "\n";
            while(inFs.hasNextLine())
            {
                help += inFs.nextLine() + "\n";
            }
        } catch (FileNotFoundException ex) {
            System.out.println(ex.getMessage());
        }
        JFrame helpFrame = new JFrame();
        JTextArea helpText = new JTextArea();
        helpText.setEnabled(false);
        helpText.setBackground(Color.white);
        helpText.setText(help);
        helpText.setBackground(Color.WHITE);
        helpText.setDisabledTextColor(Color.blue);
        Font font = helpText.getFont();
        float size = font.getSize() + 1.0f;
        helpText.setFont(font.deriveFont(size));
        helpText.setLineWrap(true);
        helpFrame.setSize(650, 250);
        helpFrame.setVisible(true);
        helpFrame.add(helpText);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        int index = this.jList1.getSelectedIndex();
        try
        {
            ClassSkeleton cs = new ClassSkeleton(classes[index]);
            String[] skelStringArr;
            if (this.mt != null)
            {
                Hashtable ht = this.mt.getHashTable();
                skelStringArr = cs.getSkeleton(ht);
            } else
            {
                skelStringArr = cs.getSkeleton();
            }

            this.jTextArea2.setText(skelStringArr[0]);
            this.jColHeader.setText(skelStringArr[1] + "\n    ");
        }
        catch (Exception ex)
        {
            throw(ex);
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.methods = null;
        this.fileName = null;
        this.parentFileName = null;
        this.grandParentFileName = null;
        this.constructors = null;
        this.url = null;
        this.ucl = null;
        this.classes = null;
        this.jList1.setListData(new String[0]);
        this.jTextArea2.setText("");
        this.jColHeader.setText("     ");
        this.mt = null;
        this.vm = null;
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.methods = null;
        this.fileName = null;
        this.parentFileName = null;
        this.grandParentFileName = null;
        this.constructors = null;
        this.url = null;
        this.ucl = null;
        this.classes = null;
        this.jList1.setListData(new String[0]);
        this.jTextArea2.setText("");
        this.jColHeader.setText("     ");
        this.mt = null;
        this.vm = null;
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int idx = this.jList1.getSelectedIndex();

        if (idx >= 0)
        {
            LaunchingConnector lc = Bootstrap.virtualMachineManager().defaultConnector();
            Map map = lc.defaultArguments();
            Connector.Argument ca = (Connector.Argument) map.get("main");

            try
            {
                int i = this.files[idx].getName().indexOf(".class");
                String cName = this.dir.getName() + "." + this.files[idx].getName().substring(0, i);
                ca.setValue("-cp \"" + this.dir.getParentFile() + "\" " + cName);
                this.vm = lc.launch(map);
                Process process = this.vm.process();
                this.vm.setDebugTraceMode(0);
                this.displayRemoteOutput(process.getInputStream());
                this.mt = new MyThread(this.vm, false, this.dir.getName(), this.files.length, this);
            } catch (Exception e)
            {
                System.out.println(e);
            }
        }
        else if (this.classes[0] != null)
        {
            JOptionPane.showMessageDialog(null, "Select a .class file on the left and press \"Run\"");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void displayRemoteOutput(final InputStream stream) {
        Thread thr = new Thread("output reader") {
            public void run() {
                BufferedReader in = new BufferedReader(new InputStreamReader(stream));
                int i;
                try {
                    while ((i = in.read()) != -1) {
                        System.out.print((char) i); // Print out standard output
                    }
                } catch (IOException ex) {
                    System.out.println("Failed reading output");
                }
            }
        };
        thr.setPriority(Thread.MAX_PRIORITY - 1);
        thr.start();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables

    public Class chooser(File f, Class c, String str1,
                                String str2, String str3, int index) throws MalformedURLException, ClassNotFoundException
    {
        while (c == null)
        {
            URLClassLoader ucl;
            if (index == 0)
            {
                url = f.getParentFile().toURI().toURL();
                URL[] urla = {url};
                ucl = new URLClassLoader(urla);
                c = Class.forName(str1, true, ucl);
            }
            if (index == 1)
            {
                url = f.getParentFile().getParentFile().toURI().toURL();
                URL[] urla = {url};
                ucl = new URLClassLoader(urla);
                c = Class.forName(str2 + "." + str1, true, ucl);
            }
            if (index == 2)
            {
                url = f.getParentFile().getParentFile().getParentFile().toURI().toURL();
                URL[] urla = {url};
                ucl = new URLClassLoader(urla);
                c = Class.forName(str3 + "." + str2 + "." + str1, true, ucl);
            }
            index++;
        }
        return c;
    }

    public void getJfc()
    {
        jfc.setFileSelectionMode(1);
        jfc.setFileFilter(filter);

        returnVal = this.jfc.showOpenDialog(this);
        if (returnVal == 0)
        {
            this.dir = this.jfc.getSelectedFile();
            this.files = this.dir.listFiles(myFileNameFilter);
            DefaultListModel dlm = new DefaultListModel();

            variablesInitializer();

            for (int i = 0; i < this.files.length; ++i)
            {
                dlm.add(i, this.files[i].getName());
                fileName[i] = this.files[i].getName().split("\\.")[0];
                parentFileName[i] = this.files[i].getParentFile().getName();
                grandParentFileName[i] = this.files[i].getParentFile().getParentFile().getName();
            }

            this.jList1.setModel(dlm);

            try
            {
                URL u = this.dir.getParentFile().toURL();
                this.urls[0] = u;
                this.ucl = new URLClassLoader(this.urls);
            } catch (Exception ex)
            {
                System.out.println(ex);
            }
        }
    }

    public void variablesInitializer()
    {
        fileName = new String[files.length];
        parentFileName = new String[files.length];
        grandParentFileName = new String[files.length];
        classes = new Class[files.length];
    }

    public void directoryParser(int index) throws MalformedURLException, ClassNotFoundException
    {
        int i = 0;
        if (returnVal == 0)
        {
            for (File f : files)
            {
                try
                {
                    classes[i] = chooser(files[i], classes[i], fileName[i],
                            parentFileName[i], grandParentFileName[i], index);
                } catch (MalformedURLException | ClassNotFoundException e)
                {
                    if (classes[i] == null)
                        throw e;
                    //System.out.println(e.getMessage());
                }

                i++;
            }
        }
    }

    public void updateNumbers() {
        int idx = this.jList1.getSelectedIndex();

        try {
            ClassSkeleton cs = new ClassSkeleton(classes[idx]);
            String[] skelStringArr;
            if (this.mt != null) {
                Hashtable ht = this.mt.getHashTable();
                skelStringArr = cs.getSkeleton(ht);
            } else {
                skelStringArr = cs.getSkeleton();
            }

            this.jColHeader.setText(skelStringArr[1] + "\n    ");
        } catch (Exception var8) {
            System.out.println(var8);
        }
    }
}
